# Generated by Django 6.0.1 on 2026-01-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='HelpDesk', max_length=100, verbose_name='Site Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Favicon')),
                ('primary_color', models.CharField(default='#3B82F6', help_text='Hex code', max_length=7, verbose_name='Primary Color')),
                ('secondary_color', models.CharField(default='#10B981', help_text='Hex code', max_length=7, verbose_name='Secondary Color')),
                ('accent_color', models.CharField(default='#F59E0B', help_text='Hex code', max_length=7, verbose_name='Accent Color')),
                ('default_timezone', models.CharField(default='UTC', max_length=50, verbose_name='Timezone')),
                ('ticket_prefix', models.CharField(default='TICKET', max_length=10, verbose_name='Ticket Prefix')),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
    ]
