# Generated by Django 6.0.1 on 2026-01-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Template Name')),
                ('template_type', models.CharField(choices=[('TICKET_CREATED', 'Ticket Created'), ('TICKET_ASSIGNED', 'Ticket Assigned'), ('TICKET_RESOLVED', 'Ticket Resolved'), ('TICKET_COMMENT', 'New Comment')], max_length=50, unique=True, verbose_name='Type')),
                ('subject_template', models.CharField(help_text='Available vars: {{ticket_id}}, {{subject}}', max_length=200, verbose_name='Subject Template')),
                ('body_template', models.TextField(help_text='HTML content. Available vars: {{ticket_id}}, {{subject}}, {{status}}', verbose_name='Body Template (HTML)')),
            ],
        ),
        migrations.CreateModel(
            name='SMTPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=200, verbose_name='SMTP Host')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='SMTP Port')),
                ('username', models.CharField(max_length=200, verbose_name='SMTP Username')),
                ('password', models.CharField(max_length=200, verbose_name='SMTP Password')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Use TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Use SSL')),
                ('default_from_email', models.EmailField(max_length=254, verbose_name='Default From Email')),
            ],
        ),
    ]
